object = "<function test at 0x7f74ee29c280>"
type = "function"
serializable_by_default = false
name = "test"
code = [ "def test(a, b):", "    return a * b", "",]
base64 = "gASVFQAAAAAAAACMCF9fbWFpbl9flIwEdGVzdJSTlC4="

[dict_class]

[args]
args = [ "a", "b",]
kwonlyargs = []

[args.annotations]
